language: node_js
os:
  - linux
  - osx
node_js:
  - 6.0.0
install:
  - npm install
before_script:
  - npm install -g bower
  - npm install -g gulp
  - bower install
  - gulp build
  - npm install -g codeclimate-test-reporter
script: gulp test
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
